### ISSUE TITLE
hello_world.pyの実行結果が正しく表示されない

### ISSUE THREAD

**Issue by akihirookuda95** [DefiosLab/Raspi4GPGPU_guide#4]
- エラー内容
```
akihiro@raspberrypi:~/work/Raspi4GPGPU_guide/chap02 $ python3 hello_world.py 
Traceback (most recent call last):
  File "hello_world.py", line 87, in <module>
    main()
  File "hello_world.py", line 54, in main
    with Driver() as drv:
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/driver.py", line 171, in __init__
    raise e
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/driver.py", line 164, in __init__
    self.memory = Memory(self.drm, total_size)
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/driver.py", line 76, in __init__
    raise e
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/driver.py", line 66, in __init__
    self.handle, self.phyaddr = drm.v3d_create_bo(size)
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/drm_v3d.py", line 143, in v3d_create_bo
    ioctl(self.fd, self.IOCTL_V3D_CREATE_BO, st)
OSError: [Errno 22] Invalid argument
```

- やったこと
  - `sudo apt update && sudo apt -y upgrade && sudo apt -y autoremove && sudo apt autoclean`
  - `sudo apt install git`
  - `sudo apt install python3-pip`
  - `sudo apt install python3-numpy`
  - `sudo apt install python3-pil`
  - `python3 -m pip install --upgrade pip setuptools wheel`
  - `python3 -m pip install git+https://github.com/Idein/py-videocore6.git`
  - `sudo usermod --append --groups video $USER`
  - `sudo reboot now`
  - `sudo raspi-config` -> set GPU memory "256"

**Comment by TakedaHiromasa** [comment]
ご報告ありがとうございます。
我々の環境でも同じエラーになるか再現してみますので、
RaspberryPi本体の名前（RaspberryPi 4B など）と`$ uname -a`の出力を共有いただけますでしょうか？

**Comment by sagamixaki** [comment]
共有します。
- 使用機器: RaspberryPi4 (4GB)
- uname -a 出力
  - `Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`

**Comment by TakedaHiromasa** [comment]
OSは`Raspberry Pi OS(Legacy)`でしょうか？
重ねてすみませんが`lsb_release -a`の出力も共有いただきたく思います。
現在手元の `Raspberry Pi 4B (4GB)` + `Raspberry Pi OS (bullseye)`では正常な動作が確認できています。

**Comment by sagamixaki** [comment]
再度、共有します。
```
akihiro@raspberrypi:~/work/Raspi4GPGPU_guide/chap02 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

```

**Comment by sagamixaki** [comment]
進捗がありましたので、共有します。
V3Dハードウェアと通信する/dev/dri/card0にアクセスしている、`~/.local/lib/python3.7/site-packages/videocore6/drm_v3d.py`
ファイルの28行目、`__init__(self, path='/dev/dri/card0')`の部分を、`__init__(self, path='/dev/dri/card1')`と変更したところ、以下の出力を得ました。
```
akihiro@raspberrypi:~/work/Raspi4GPGPU_guide/chap02 $ python3 hello_world.py 
====================================== a =======================================
[0.36496288 0.20586325 0.48385605 0.62278444 0.71718633 0.98592323
 0.06370725 0.20594344 0.20398544 0.6259714  0.770832   0.80539465
 0.60546494 0.20336767 0.6887281  0.6713718 ]
====================================== b =======================================
[0.5355196  0.72511923 0.24376498 0.7471335  0.09779646 0.7643241
 0.5094759  0.38006684 0.791653   0.5683779  0.42135978 0.87689763
 0.62957174 0.22059354 0.97825134 0.13572368]
===================================== a+b ======================================
[0.9004825  0.9309825  0.727621   1.3699179  0.8149828  1.7502474
 0.5731831  0.5860103  0.99563843 1.1943493  1.1921918  1.6822922
 1.2350366  0.42396122 1.6669794  0.8070955 ]
==================================== error =====================================
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```
ちなみに、card0, card1の役割の違いが分かっていないので、根本的な解決になっているか分かりません。

**Comment by sagamixaki** [comment]
久しぶりに、hello_world.pyを実行したところ、エラーが生じました。
```
Traceback (most recent call last):
  File "hello_world.py", line 87, in <module>
    main()
  File "hello_world.py", line 54, in main
    with Driver() as drv:
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/driver.py", line 171, in __init__
    raise e
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/driver.py", line 164, in __init__
    self.memory = Memory(self.drm, total_size)
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/driver.py", line 76, in __init__
    raise e
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/driver.py", line 66, in __init__
    self.handle, self.phyaddr = drm.v3d_create_bo(size)
  File "/home/akihiro/.local/lib/python3.7/site-packages/videocore6/drm_v3d.py", line 143, in v3d_create_bo
    ioctl(self.fd, self.IOCTL_V3D_CREATE_BO, st)
OSError: [Errno 22] Invalid argument

```
`~/.local/lib/python3.7/site-packages/videocore6/drm_v3d.py`28行目、`__init__(self, path='/dev/dri/card1')`の部分を、`__init__(self, path='/dev/dri/card0')`と変更したところ、以下の出力を得ました。
```
====================================== a =======================================
[0.08070911 0.5549537  0.16028278 0.31827158 0.18690239 0.05505155
 0.31323674 0.26421943 0.42112496 0.18440719 0.7417391  0.7249522
 0.32439196 0.38844505 0.90648293 0.03453559]
====================================== b =======================================
[0.30819303 0.38619387 0.9643609  0.8225637  0.40758154 0.41293374
 0.5824282  0.27636176 0.6526179  0.01532564 0.09996289 0.40097407
 0.09097959 0.4171238  0.43688527 0.38082013]
===================================== a+b ======================================
[0.38890213 0.94114757 1.1246437  1.1408353  0.5944839  0.4679853
 0.89566493 0.5405812  1.0737429  0.19973284 0.841702   1.1259263
 0.41537154 0.8055688  1.3433682  0.4153557 ]
==================================== error =====================================
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

```
